### ISSUE TITLE
Doesn't work v2.0.4 (stable)

### ISSUE THREAD

**Issue by zakiaziz** [lkzhao/hyperterm-alternatescroll#13]
No, errors or anything. Just doesn't work.

**Comment by simonhaenisch** [comment]
After starting `nano`, I get this error in the dev tools:

```
TypeError: Cannot read property 'prefs_' of undefined
    at Object.componentWillReceiveProps (/Users/simonhaenisch/.hyper_plugins/node_modules/hyperterm-alternatescroll/index.js:151:18)
    at updateClassInstance (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:54251)
    at beginWork (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:56960)
    at e (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:69619)
    at k (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:70127)
    at p (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:70641)
    at y (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:72669)
    at D (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:72195)
    at Object.enqueueSetState (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:53056)
    at Connect.v.setState (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:20900)
```

After that I get a notification that all plugins that decorate `<Term/>` have been disabled:

> [Notification] Plugin error: Plugins decorating Term has been disabled because of a plugin crash. Check Developer Tools for details.

**Comment by matmunn** [comment]
Having the same issue

**Comment by matmunn** [comment]
I've done some digging, I think the problem is because of the change from hterm to xterm.js in Hyper Terminal. I'll have more of a play when I get a chance.

**Comment by matmunn** [comment]
If you edit `~/.vimrc` and add `set mouse=a` you'll be able to scroll vim. It doesn't seem to move the cursor, but lets you scroll the document.

**Comment by rightaway** [comment]
Is this still maintained?
