### ISSUE TITLE
JS Error in 0.8.0.733: parentProps.sessions.forEach is not a function

### ISSUE THREAD

**Issue by rtvenge** [lkzhao/hyperterm-alternatescroll#5]
Hello,

Thanks for this great plugin! I updated to the latest version of HyperTerm that _just_ came out and I'm seeing a bunch of JS errors. Maybe they changed an API or something? Just thought I'd bring it up, not urgent for me anyway. Here's the error that gets repeated a bunch of times in the console:

```
bundle.js:731 TypeError: parentProps.sessions.forEach is not a function
    at exports.getTermProps (/Users/rtvenge/dotfiles/.hyperterm_plugins/node_modules/hyperterm-alternatescroll/index.js:68:24)
    at termPropsDecorators.forEach.err (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:729:14)
    at Array.forEach (native)
    at getTermGroupProps (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:721:23)
    at __WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement.props.termGroups.map.termGroup (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:16866:111)
    at Array.map (native)
    at Terms.template (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:16863:29)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:43172:32)
    at ReactCompositeComponentWrapper._renderValidatedComponent (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:43195:34)
    at ReactCompositeComponentWrapper._updateRenderedComponent (file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:43119:36)termPropsDecorators.forEach.err @ bundle.js:731getTermGroupProps @ bundle.js:721__WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement.props.termGroups.map.termGroup @ bundle.js:16866template @ bundle.js:16863_renderValidatedComponentWithoutOwnerOrContext @ bundle.js:43172_renderValidatedComponent @ bundle.js:43195_updateRenderedComponent @ bundle.js:43119_performComponentUpdate @ bundle.js:43097updateComponent @ bundle.js:43018receiveComponent @ bundle.js:42920receiveComponent @ bundle.js:2881_updateRenderedComponent @ bundle.js:43127_performComponentUpdate @ bundle.js:43097updateComponent @ bundle.js:43018receiveComponent @ bundle.js:42920receiveComponent @ bundle.js:2881_updateRenderedComponent @ bundle.js:43127_performComponentUpdate @ bundle.js:43097updateComponent @ bundle.js:43018performUpdateIfNecessary @ bundle.js:42934performUpdateIfNecessary @ bundle.js:2913runBatchedUpdates @ bundle.js:1722perform @ bundle.js:3632perform @ bundle.js:3632flushBatchedUpdates @ bundle.js:1744closeAll @ bundle.js:3698perform @ bundle.js:3645batchedUpdates @ bundle.js:45947enqueueUpdate @ bundle.js:1772enqueueUpdate @ bundle.js:7073enqueueSetState @ bundle.js:7258ReactComponent.setState @ bundle.js:6325handleChange @ bundle.js:40219dispatch @ bundle.js:14215action @ bundle.js:9284(anonymous function) @ index.js:40(anonymous function) @ index.js:158action @ index.js:37(anonymous function) @ index.js:24action @ bundle.js:969(anonymous function) @ bundle.js:3748__WEBPACK_IMPORTED_MODULE_5__rpc__.a.on.data @ bundle.js:17499emitOne @ events.js:96emit @ events.js:188ipcListener @ bundle.js:18470emitTwo @ events.js:106emit @ events.js:191
bundle.js:5313 [Notification] Plugin error: hyperterm-alternatescroll: Error occurred in `getTermGroupProps`. Check Developer Tools for details.
```

**Comment by benjamine** [comment]
+1

**Comment by muescha** [comment]
+1

**Comment by nugrahawahyu** [comment]
+1

**Comment by JiLiZART** [comment]
+1

**Comment by JiLiZART** [comment]
@lkzhao any plans to fix it?

**Comment by lkzhao** [comment]
I will come back to this in a couple of days. Doesn't seem to be an easy fix. I am not really sure whats changed in Hyper. so I have to spend some time to dig deeper.

**Comment by JiLiZART** [comment]
Thanks!

**Comment by lkzhao** [comment]
Should be working now with v1.3.0!
